services:
  adminer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminer-app-host
    ports:
      - "8060:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    # Add host.docker.internal for Linux compatibility
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Use host networking to access databases on the host
    # NOTE: When using network_mode: host, the ports section is ignored
    # and Adminer will be available on port 80 of the host
    # network_mode: host

# Alternative: Use external network
# services:
#   adminer:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: adminer-app-external
#     ports:
#       - "8061:80"
#     environment:
#       - APACHE_DOCUMENT_ROOT=/var/www/html
#     restart: unless-stopped
#     networks:
#       - default
#       - external-network
#
# networks:
#   external-network:
#     external: true
#     name: your-mysql-network-name